"""Generate pre-computed gallery data as JSON for the web app.

This script runs the 5 DGP functions from src/utils/gallery.py,
serializes the results, and writes a gallery_data.js file that can be
loaded directly in the browser without Pyodide.
"""

from __future__ import annotations

import json
import sys
from pathlib import Path

# Add project root to path
sys.path.insert(0, str(Path(__file__).resolve().parent.parent))

from src.utils.gallery import get_gallery_items


def make_json_safe(obj):
    """Recursively convert numpy types to JSON-safe Python types."""
    import numpy as np
    if isinstance(obj, (np.integer,)):
        return int(obj)
    if isinstance(obj, (np.floating,)):
        return float(obj)
    if isinstance(obj, (np.bool_,)):
        return bool(obj)
    if isinstance(obj, np.ndarray):
        return obj.tolist()
    if isinstance(obj, dict):
        return {str(k): make_json_safe(v) for k, v in obj.items()}
    if isinstance(obj, (list, tuple)):
        return [make_json_safe(v) for v in obj]
    return obj


def main():
    items = get_gallery_items()

    all_data = []
    for item in items:
        # Convert data to list of lists (rows)
        data_list = [list(item.data.columns)]
        for _, row in item.data.iterrows():
            data_list.append([_safe_val(v) for v in row])

        # Variable type info
        col_types = {}
        for col in item.data.columns:
            series = item.data[col]
            import pandas as pd
            if pd.api.types.is_numeric_dtype(series):
                col_types[col] = "numeric"
            else:
                col_types[col] = "categorical"

        all_data.append({
            "id": item.id,
            "title": item.title,
            "persona": item.persona,
            "persona_icon": item.persona_icon,
            "description": item.description,
            "tags": item.tags,
            "n_obs": item.n_obs,
            "story": item.story,
            "key_features": item.key_features,
            "dep_var": item.dep_var,
            "indep_vars": [v for v in item.data.columns if v != item.dep_var],
            "columns": [str(c) for c in item.data.columns],
            "column_types": col_types,
            "data": data_list,
            "result": make_json_safe(item.result_json),
        })

    # Write as JS file
    js_content = "// Generated gallery data for Regression Analysis Web App\n"
    js_content += "// Do not edit manually -- generated by scripts/generate_gallery_json.py\n\n"
    js_content += "const GALLERY_DATA = "
    js_content += json.dumps(all_data, ensure_ascii=False, indent=2)
    js_content += ";\n"

    output_path = Path(__file__).resolve().parent.parent / "web" / "js" / "gallery_data.js"
    with open(output_path, "w", encoding="utf-8") as f:
        f.write(js_content)

    print(f"Generated {output_path} with {len(all_data)} gallery items.")


def _safe_val(v):
    """Convert values to JSON-safe types."""
    import numpy as np
    import pandas as pd
    if pd.isna(v):
        return None
    if isinstance(v, (np.integer,)):
        return int(v)
    if isinstance(v, (np.floating,)):
        return float(v)
    if isinstance(v, (np.bool_,)):
        return bool(v)
    if isinstance(v, np.ndarray):
        return v.tolist()
    return v


if __name__ == "__main__":
    main()
